[project]
name = "preferenceguidancediffusion"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=4.4.2",
    "diffusers>=0.36.0",
    "omegaconf>=2.3.0",
    "torch>=2.9.1",
    "tqdm>=4.67.1",
    "transformers>=4.57.3",
]

[[tool.uv.index]]
name = "westlake"
url = "https://mirrors2.westlake.edu.cn/pypi/simple"

[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple"
default = true


[dependency-groups]
image-reward = [
    "image-reward",
]
